# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9872e3188456ce257454cb33e8a9da471463aebc856aacbaeb6292236685dc90e19b7afcb5f668f0ad788a5aae91a71c080124e5aeef597051853f0477c03fdb

test:
  secret_key_base: dcf6567aa8e796d74b6f83c8df94a94a7b95e8a5a6707e8a3dbc5d0c835af400ea570ff5537dec0cac56f0045ebe12758d260436ab6bd5626d2b0fe961eda645

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
